### PR TITLE
Add Acceleration to calculating desiredHeading

### PR DESCRIPTION
**Pull request by linglejack06**
**Summary**: add acceleration defined in Telemetry class to CommandSwerveDrivetrain and use in calculations (x = vt + 0.5 * a * t * t)

**Changes**
- add robot acceleration supplier to drivetrain
- add the acceleration part of calculation to robot velocity adjusted translation2d

**resolves** #81

### CODE REVIEW

**Review by jkleiber — COMMENTED** [review]
This looks like it should work, but I want to test on the robot before Approving

If this isn't necessary/causes problems, it may be worth it to add a feature flag for turning this on/off

**Comment by linglejack06** [comment]
ok, makes sense.

**Comment by jkleiber** [comment]
@linglejack06 today we were testing other features but noticed that the pigeon acceleration wasn't being read. It also turned out that the velocity estimate was sufficient for shoot on the move to work fairly well, so we likely don't need this feature.

My recommendation is to close this PR and the associated ticket as wontfix. Thanks for writing this code so we had it in our back pocket if needed!

**Comment by linglejack06** [comment]
ok, ill close both.

**Pull request closed without merging**
