### PR TITLE
Align drivetrain to various targets

### PR DESCRIPTION
**Pull request by aidnem**
This adds two new systems to the drive subsystem:
- alignState, to keep track of whether we are currently aligning or in manual alignment mode
- alignTarget, to keep track of which target we are aligned at.

This is still a work in progress as:
- amp heading and source headings need to be checked
- Other items such as drift correction from the original issue need to be planned & implemented

With that said, using the right bumper to toggle alignment on/off and using POV to select targets appears to be working in the sim:

https://github.com/team401/2024-Robot-Code/assets/99768676/678bba4a-81c0-4235-bae5-2896881e2f2b

### CODE REVIEW

**Comment by aidnem** [comment]
Source headings should now have correct values as well (see [8292fe5](https://github.com/team401/2024-Robot-Code/pull/75/commits/8292fe53a63b1ce88e49887280e347ff0bb1ae5f)), as shown with the robot aligning to source in sim below:
image

**Comment by redPlover** [comment]
This looks really good. 👍

**Review by jkleiber — COMMENTED** [review]
Just one comment on the amp headings

**Comment by PChild** [comment]
This may have already been handled but if not can we update the amp align values to account for the amp scoring side of the robot being opposite the speaker scoring side?

**Comment by aidnem** [comment]
@PChild I've corrected amp headings to both be facing the same direction, but they're both in terms of the front of the robot right now (same face as speaking aiming). We can check the directions tonight and sort it all out.

**Review by charlesmackenzie — APPROVED** [review]
bonne

**Review by charlesmackenzie — APPROVED** [review]
bonne again

**Pull request merged**
