### PR TITLE
Add Uptake Sensor 

### LINKED ISSUE #149: Integrate note sensor in uptake and prevent multiple note intake
**Purpose**
The purpose of this addition is to add note sensor support in the uptake so we don't get a ton of technical fouls

**Project Scope**
- [x] Add support for a sensor to detect notes in the uptake
- [x] Include this sensor in logic for the intake to prevent the robot from picking up multiple notes
  - [x] If a note is in the uptake and shooter deck, run the uptake and intake backwards to get rid of the note
  - [x] If a note is in the uptake, run the intake motor(s) that touch notes on the ground backwards

### PR DESCRIPTION
**Pull request by linglejack06**
**Summary**: add sensor to uptake to prevent intake from running with note already in. This will prevent tech fouls.

**Changes**:
- add time of flight sensor library from playingWithFusion
- add Time of Flight sensor to IntakeIOSparkMax class
- add boolean supplier for intake to check if note in shooter deck
- add check in idle mode (don't set intake action if note is sensed in uptake)
- add check in reversing state for note in shooter deck (if so run belt backwards)

Resolves #149

### CODE REVIEW

**Comment by redPlover** [comment]
@linglejack06 Could you please put the ToF sensor in the intake io instead of making a new sensor io?

This is my personal opinion though, what do you think @jkleiber?

**Comment by jkleiber** [comment]
I agree, let's put it in the Intake IO if possible

**Comment by linglejack06** [comment]
Yeah I'll change that

**Comment by jkleiber** [comment]
@wrob3rts just fyi: if you figure out how to interface with the sensor, this is the relevant PR

**Comment by jkleiber** [comment]
@linglejack06 on Saturday we saw that the Time of Flight sensor was causing weird problems on the kit bot. Apparently other teams have seen it take 30+% more CPU usage when it is in use as well.

I think we are going to add a banner sensor or a beam break to the uptake. @PChild probably has more details, but let's create a separate branch for a PR that uses a banner sensor instead and keep this PR in our pocket in case the ToF sensor comes back in scope

**Comment by linglejack06** [comment]
okay ill add that PR shortly.

**Comment by PChild** [comment]
We got one of the beam breaks installed today in the shooter deck for indexing, its working well and was drop in replace from the banner sensor. I think we can go ahead and close this PR and just go with #163

**Comment by PChild** [comment]
Closing this one in favor of #163 feel free to re-open if we need this for some reason.

**Pull request closed without merging**
