### PR TITLE
Integrates auto with real robot

### PR DESCRIPTION
**Pull request by redPlover**

### CODE REVIEW

**Comment by redPlover** [comment]
@jkleiber I would like to wait till tomorrow to merge this if that's okay. We were doing some weird stuff with checkpoints (that's why the arm was going all the way down at some points). If removing them breaks the cool auto then I can just roll-back really quickly. The only reason I would look at this before Blacksburg is that I don't know what would happen if we tried an untested auto.

**Comment by jkleiber** [comment]
Sounds good 👍

**Comment by jkleiber** [comment]
How did this go today?

**Comment by redPlover** [comment]
> How did this go today?

I was unfortunately unable to test auto. We were integrating cameras and mechanical needed to do some stuff with the hood and shooter deck.

**Pull request merged**
