### PR TITLE
 Adds tunable modes

### PR DESCRIPTION
**Pull request by redPlover**

### CODE REVIEW

**Comment by redPlover** [comment]
@jkleiber Is my implementation of slots in the tunable class okay or should I do this another way? The slots essentially specify what IO you want to call in case there are multiple IOs in a single subsystem.

The command runs:
<pre>
controller.a()
     .onTrue(new TuneS(scoringSubsystem, slot));
</pre>

The command calls the subsystem:
<pre>
startPosition = subsystem.getPosition(slot);
</pre>

The subsystem returns the value:
<pre>
@Override
public double getPosition(int slot) {
    switch (slot) {
        // Aimer
        case 0:
            return aimerInputs.aimAngleRad;
        // Hood
        case 1:
            return hoodInputs.hoodAngleRad;
        // Shooter
        case 2:
            return shooterInputs.shooterLeftVelocityRPM;
    }
    return 0.0;
}
</pre>

**Comment by jkleiber** [comment]
@redPlover the slots idea seems good to me

**Comment by jkleiber** [comment]
Are there any cases where we would want multiple slots enabled at the same time?

**Comment by redPlover** [comment]
> Are there any cases where we would want multiple slots enabled at the same time?

Probably not, I can't think of a time when we'd need to

**Comment by redPlover** [comment]
I would like to merge this without adding more features if that's okay (we could also wait till shop tomorrow) because this is a large PR and I don't want more merge errors for others working on their stuff. Some of the test features have been tested with the hood and work.

https://github.com/team401/2024-Robot-Code/assets/100500945/ef92299f-b1b9-490b-8851-893b7cee1820

**Review by jkleiber — APPROVED** [review]
Ngl I didn't read most of this, but approved anyway since this is changing test mode and shouldn't break the main code

**Pull request merged**
